/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistraFarmaciaRouteImport } from './routes/registra-farmacia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedAssistitiRouteImport } from './routes/_authenticated/assistiti'
import { Route as AuthenticatedAssistitiIdRouteImport } from './routes/_authenticated/assistiti.$id'
import { Route as AuthenticatedAdminFarmacieRouteImport } from './routes/_authenticated/admin.farmacie'

const RegistraFarmaciaRoute = RegistraFarmaciaRouteImport.update({
  id: '/registra-farmacia',
  path: '/registra-farmacia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistitiRoute = AuthenticatedAssistitiRouteImport.update({
  id: '/assistiti',
  path: '/assistiti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistitiIdRoute =
  AuthenticatedAssistitiIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAssistitiRoute,
  } as any)
const AuthenticatedAdminFarmacieRoute =
  AuthenticatedAdminFarmacieRouteImport.update({
    id: '/admin/farmacie',
    path: '/admin/farmacie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/registra-farmacia': typeof RegistraFarmaciaRoute
  '/assistiti': typeof AuthenticatedAssistitiRouteWithChildren
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/admin/farmacie': typeof AuthenticatedAdminFarmacieRoute
  '/assistiti/$id': typeof AuthenticatedAssistitiIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/registra-farmacia': typeof RegistraFarmaciaRoute
  '/assistiti': typeof AuthenticatedAssistitiRouteWithChildren
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/farmacie': typeof AuthenticatedAdminFarmacieRoute
  '/assistiti/$id': typeof AuthenticatedAssistitiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/registra-farmacia': typeof RegistraFarmaciaRoute
  '/_authenticated/assistiti': typeof AuthenticatedAssistitiRouteWithChildren
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/farmacie': typeof AuthenticatedAdminFarmacieRoute
  '/_authenticated/assistiti/$id': typeof AuthenticatedAssistitiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/registra-farmacia'
    | '/assistiti'
    | '/impostazioni'
    | '/admin/farmacie'
    | '/assistiti/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/registra-farmacia'
    | '/assistiti'
    | '/impostazioni'
    | '/'
    | '/admin/farmacie'
    | '/assistiti/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/registra-farmacia'
    | '/_authenticated/assistiti'
    | '/_authenticated/impostazioni'
    | '/_authenticated/'
    | '/_authenticated/admin/farmacie'
    | '/_authenticated/assistiti/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegistraFarmaciaRoute: typeof RegistraFarmaciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registra-farmacia': {
      id: '/registra-farmacia'
      path: '/registra-farmacia'
      fullPath: '/registra-farmacia'
      preLoaderRoute: typeof RegistraFarmaciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistiti': {
      id: '/_authenticated/assistiti'
      path: '/assistiti'
      fullPath: '/assistiti'
      preLoaderRoute: typeof AuthenticatedAssistitiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistiti/$id': {
      id: '/_authenticated/assistiti/$id'
      path: '/$id'
      fullPath: '/assistiti/$id'
      preLoaderRoute: typeof AuthenticatedAssistitiIdRouteImport
      parentRoute: typeof AuthenticatedAssistitiRoute
    }
    '/_authenticated/admin/farmacie': {
      id: '/_authenticated/admin/farmacie'
      path: '/admin/farmacie'
      fullPath: '/admin/farmacie'
      preLoaderRoute: typeof AuthenticatedAdminFarmacieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAssistitiRouteChildren {
  AuthenticatedAssistitiIdRoute: typeof AuthenticatedAssistitiIdRoute
}

const AuthenticatedAssistitiRouteChildren: AuthenticatedAssistitiRouteChildren =
  {
    AuthenticatedAssistitiIdRoute: AuthenticatedAssistitiIdRoute,
  }

const AuthenticatedAssistitiRouteWithChildren =
  AuthenticatedAssistitiRoute._addFileChildren(
    AuthenticatedAssistitiRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistitiRoute: typeof AuthenticatedAssistitiRouteWithChildren
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminFarmacieRoute: typeof AuthenticatedAdminFarmacieRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistitiRoute: AuthenticatedAssistitiRouteWithChildren,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminFarmacieRoute: AuthenticatedAdminFarmacieRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegistraFarmaciaRoute: RegistraFarmaciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
